server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 120.46.149.32:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启配置中心
          lower-case-service-id: true
      routes:
        - id: diners
          uri: lb://diners
          predicates:
            - Path=/diners/**
          filters:
            - StripPrefix=1
        - id: oauth2-server
          uri: lb://oauth2-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1



secure:
  ignore:
    urls: # 配置白名单路径
      - /actuator/**
      - /auth/oauth/**
      - /diners/signin
      - /diners/send
      - /diners/checkPhone
      - /diners/register


logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'