server:
  port: 8082

spring:
  application:
    name: oauth2-server
  cloud:
    nacos:
      server-addr: 120.46.149.32:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: guofei??
    url: jdbc:mysql://120.46.149.32:3307/diners?serverTimezone=GMT%2B8
  # Redis
  redis:
    port: 6380
    host: 120.46.149.32
    timeout: 3000
    database: 1
    password: guofei??


# Oauth2
client:
  oauth2:
    client-id: appId # 客户端标识 ID
    secret: 123456 # 客户端安全码
    # 授权类型
    grant_types:
      - password
      - refresh_token
    # token 有效时间，单位秒
    token-validity-time: 3600
    refresh-token-validity-time: 3600
    # 客户端访问范围
    scopes:
      - api
      - all


# 指标监控健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露的端点

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'